version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-guitartortona-local
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: mydb
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: