spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: myuser
    password: mypass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true