apiVersion: apps/v1
kind: Deployment
metadata:
  name: guitartortona-api
  labels:
    environment: production
spec:
  replicas: 2  # Production ha più repliche
  template:
    metadata:
      labels:
        environment: production
    spec:
      containers:
      - name: api
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://mariadb.databases.svc.cluster.local:3306/guitartortona"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"