apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/mmzitarosa/guitartortona-api
    newTag: latest  # Sarà aggiornato da GitHub Actions