apiVersion: apps/v1
kind: Deployment
metadata:
  name: guitartortona-api
  labels:
    app: guitartortona-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guitartortona-api
  template:
    metadata:
      labels:
        app: guitartortona-api
    spec:
      containers:
      - name: api
        image: ghcr.io/mmzitarosa/guitartortona-api:latest  # Sarà sovrascritto da Kustomize
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.mariadb.jdbc.Driver"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.MariaDBDialect"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: password
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5