apiVersion: v1
kind: Service
metadata:
  name: guitartortona-api
  labels:
    app: guitartortona-api
spec:
  selector:
    app: guitartortona-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP