name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      staging_version:
        description: 'Staging version to promote (e.g., 1.3.0-rc3)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      prod_version: ${{ steps.version.outputs.prod_version }}
      source_branch: ${{ steps.branch.outputs.source_branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Validate version format
        id: version
        run: |
          VERSION="${{ github.event.inputs.staging_version }}"
          
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
            echo "❌ Error: Invalid version format. Must be X.Y.Z-rcN"
            exit 1
          fi
          
          PROD_VERSION=${VERSION%-rc*}
          echo "prod_version=$PROD_VERSION" >> $GITHUB_OUTPUT
          echo "staging_version=$VERSION" >> $GITHUB_OUTPUT
          
          echo "✅ Staging version: $VERSION"
          echo "✅ Production version: $PROD_VERSION"

      - name: Verify tag exists
        run: |
          VERSION="${{ github.event.inputs.staging_version }}"
          
          if ! git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo "❌ Error: Tag v${VERSION} does not exist"
            exit 1
          fi
          
          echo "✅ Tag v${VERSION} exists"

      - name: Verify Docker image exists
        run: |
          VERSION="${{ github.event.inputs.staging_version }}"
          
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          
          if ! docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}; then
            echo "❌ Error: Docker image ${VERSION} does not exist in registry"
            exit 1
          fi
          
          echo "✅ Docker image ${VERSION} exists"

      - name: Determine source branch
        id: branch
        run: |
          VERSION="${{ github.event.inputs.staging_version }}"
          
          TAG_COMMIT=$(git rev-list -n 1 "v${VERSION}")
          
          if git branch -r --contains $TAG_COMMIT | grep -q "origin/hotfix"; then
            SOURCE_BRANCH="hotfix"
          else
            SOURCE_BRANCH="develop"
          fi
          
          echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
          echo "✅ Source branch: $SOURCE_BRANCH"

  deploy-production:
    needs: validate
    runs-on: [self-hosted, linux, k8s]
    steps:
      - name: Retag Docker image for production
        run: |
          STAGING_VERSION="${{ github.event.inputs.staging_version }}"
          PROD_VERSION="${{ needs.validate.outputs.prod_version }}"
          
          STAGING_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${STAGING_VERSION}
          PROD_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${PROD_VERSION}
          LATEST_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          
          docker pull $STAGING_IMAGE
          docker tag $STAGING_IMAGE $PROD_IMAGE
          docker tag $STAGING_IMAGE $LATEST_IMAGE
          
          docker push $PROD_IMAGE
          docker push $LATEST_IMAGE
          
          echo "✅ Retagged images:"
          echo "  - $PROD_IMAGE"
          echo "  - $LATEST_IMAGE"

      - name: Install kubectl
        run: |
          if ! command -v kubectl &> /dev/null; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi

      - name: Deploy to Production
        run: |
          PROD_VERSION="${{ needs.validate.outputs.prod_version }}"
          
          kubectl set image deployment/guitartortona-api \
            guitartortona-api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${PROD_VERSION} \
            -n default
          
          kubectl rollout status deployment/guitartortona-api -n default --timeout=300s
          
          echo "✅ Deployed version $PROD_VERSION to production"

  create-release-pr:
    needs: [validate, deploy-production]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.validate.outputs.source_branch }}
          fetch-depth: 0

      - name: Create production tag on source branch
        run: |
          PROD_VERSION="${{ needs.validate.outputs.prod_version }}"
          STAGING_VERSION="${{ github.event.inputs.staging_version }}"
          SOURCE_BRANCH="${{ needs.validate.outputs.source_branch }}"
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git tag -a "v${PROD_VERSION}" -m "Production Release v${PROD_VERSION}

          🚀 Promoted from staging: v${STAGING_VERSION}
          📦 Source branch: ${SOURCE_BRANCH}
          
          🌐 Production: https://api.guitar.lab
          🐳 Docker Images:
             - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${PROD_VERSION}
             - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          "
          
          git push origin "v${PROD_VERSION}"
          
          echo "✅ Created production tag: v${PROD_VERSION}"

      - name: Create Pull Request to main
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/v${{ needs.validate.outputs.prod_version }}
          base: main
          title: "🚀 Release v${{ needs.validate.outputs.prod_version }}"
          body: |
            ## 🚀 Production Release v${{ needs.validate.outputs.prod_version }}
            
            **Promoted from staging:** `${{ github.event.inputs.staging_version }}`  
            **Source branch:** `${{ needs.validate.outputs.source_branch }}`
            
            ### ✅ Deployment Status
            - **Production deployed:** ✅ https://api.guitar.lab
            - **Docker images tagged:** ✅
              - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.validate.outputs.prod_version }}`
              - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest`
            
            ### 🤖 Auto-Merge
            This PR will be automatically merged using **merge commit** to update main branch.
            
            ---
            *This is an automated release PR created by the promote-to-production workflow.*
          labels: |
            release
            automated
          draft: false

      - name: Enable auto-merge with merge commit
        run: |
          PR_NUMBER=${{ steps.create-pr.outputs.pull-request-number }}
          
          echo "Enabling auto-merge for PR #${PR_NUMBER} with merge commit strategy"
          
          gh pr merge ${PR_NUMBER} --auto --merge --delete-branch
          
          echo "✅ Auto-merge enabled with merge commit"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for PR merge
        run: |
          PR_NUMBER=${{ steps.create-pr.outputs.pull-request-number }}
          
          echo "⏳ Waiting for PR #${PR_NUMBER} to be merged..."
          echo "PR URL: https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
          
          for i in {1..60}; do
            sleep 5
          
            STATE=$(gh pr view ${PR_NUMBER} --json state --jq .state 2>/dev/null || echo "UNKNOWN")
          
            if [ "$STATE" == "MERGED" ]; then
              echo ""
              echo "✅ PR #${PR_NUMBER} merged successfully with merge commit!"
              exit 0
            fi
          
            if [ "$STATE" == "CLOSED" ]; then
              echo ""
              echo "❌ PR was closed without merging!"
              exit 1
            fi
          
            if [ "$STATE" == "UNKNOWN" ]; then
              echo "  Check $i/60: Unable to get PR state, retrying..."
            else
              echo "  Check $i/60: PR state is $STATE, waiting for merge..."
            fi
          done
          
          echo ""
          echo "⚠️  PR not merged after 5 minutes"
          echo "Check manually: https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
          exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-branches:
    needs: [validate, create-release-pr]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sync develop with main
        run: |
          PROD_VERSION="${{ needs.validate.outputs.prod_version }}"
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          echo "Syncing develop with main..."
          git fetch origin develop
          git checkout develop
          git merge origin/main --no-edit -m "chore: sync develop with production v${PROD_VERSION}"
          git push origin develop
          
          echo "✅ Synced develop with main (production v${PROD_VERSION})"

      - name: Sync hotfix with main
        run: |
          PROD_VERSION="${{ needs.validate.outputs.prod_version }}"
          
          echo "Syncing hotfix with main..."
          git fetch origin hotfix
          git checkout hotfix
          git merge origin/main --no-edit -m "chore: sync hotfix with production v${PROD_VERSION}"
          git push origin hotfix
          
          echo "✅ Synced hotfix with main (production v${PROD_VERSION})"

  create-github-release:
    needs: [validate, sync-branches]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          PROD_VERSION="${{ needs.validate.outputs.prod_version }}"
          STAGING_VERSION="${{ github.event.inputs.staging_version }}"
          
          # Get commits between staging tag and production tag
          COMMITS=$(git log --oneline "v${STAGING_VERSION}^..v${PROD_VERSION}" 2>/dev/null || echo "No commits found")
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.validate.outputs.prod_version }}
          release_name: Release v${{ needs.validate.outputs.prod_version }}
          body: |
            ## 🚀 Production Release v${{ needs.validate.outputs.prod_version }}
            
            **Promoted from staging:** `${{ github.event.inputs.staging_version }}`  
            **Source branch:** `${{ needs.validate.outputs.source_branch }}`
            
            ### 🌐 Deployment
            - **Production:** https://api.guitar.lab
            - **Staging:** https://api-staging.guitar.lab
            
            ### 📦 Docker Images
            ```
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.validate.outputs.prod_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ```