apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/mmzitarosa/guitartortona-api
    newTag: 1.2.0-rc2